apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      app: message-service
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager
      port: web
